// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/go_server/calculator.proto

package calculator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    int32    `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c384c63a91067a, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *AddRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *AddRequest) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

type AddResponse struct {
	Results              int32    `protobuf:"varint,1,opt,name=results,proto3" json:"results,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c384c63a91067a, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetResults() int32 {
	if m != nil {
		return m.Results
	}
	return 0
}

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MultipleRequest struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultipleRequest) Reset()         { *m = MultipleRequest{} }
func (m *MultipleRequest) String() string { return proto.CompactTextString(m) }
func (*MultipleRequest) ProtoMessage()    {}
func (*MultipleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c384c63a91067a, []int{2}
}

func (m *MultipleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleRequest.Unmarshal(m, b)
}
func (m *MultipleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleRequest.Marshal(b, m, deterministic)
}
func (m *MultipleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleRequest.Merge(m, src)
}
func (m *MultipleRequest) XXX_Size() int {
	return xxx_messageInfo_MultipleRequest.Size(m)
}
func (m *MultipleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleRequest proto.InternalMessageInfo

func (m *MultipleRequest) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *MultipleRequest) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type MultipleResponse struct {
	Results              int32    `protobuf:"varint,1,opt,name=results,proto3" json:"results,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultipleResponse) Reset()         { *m = MultipleResponse{} }
func (m *MultipleResponse) String() string { return proto.CompactTextString(m) }
func (*MultipleResponse) ProtoMessage()    {}
func (*MultipleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52c384c63a91067a, []int{3}
}

func (m *MultipleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipleResponse.Unmarshal(m, b)
}
func (m *MultipleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipleResponse.Marshal(b, m, deterministic)
}
func (m *MultipleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipleResponse.Merge(m, src)
}
func (m *MultipleResponse) XXX_Size() int {
	return xxx_messageInfo_MultipleResponse.Size(m)
}
func (m *MultipleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultipleResponse proto.InternalMessageInfo

func (m *MultipleResponse) GetResults() int32 {
	if m != nil {
		return m.Results
	}
	return 0
}

func (m *MultipleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "calculator.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "calculator.AddResponse")
	proto.RegisterType((*MultipleRequest)(nil), "calculator.MultipleRequest")
	proto.RegisterType((*MultipleResponse)(nil), "calculator.MultipleResponse")
}

func init() { proto.RegisterFile("proto/go_server/calculator.proto", fileDescriptor_52c384c63a91067a) }

var fileDescriptor_52c384c63a91067a = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcf, 0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x4f, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x03, 0x4b, 0x09, 0x71, 0x21, 0x44, 0x94, 0xcc, 0xb8,
	0xb8, 0x1c, 0x53, 0x52, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x78, 0xb8, 0x18, 0x13,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x18, 0x13, 0x41, 0xbc, 0x24, 0x09, 0x26, 0x08, 0x2f,
	0x09, 0xc4, 0x4b, 0x96, 0x60, 0x86, 0xf0, 0x92, 0x95, 0x1c, 0xb9, 0xb8, 0xc1, 0xfa, 0x8a, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x8b, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x8a, 0xa1,
	0xda, 0x61, 0x5c, 0x90, 0x4c, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x2a, 0xd8, 0x28, 0xce, 0x20,
	0x18, 0x57, 0x49, 0x97, 0x8b, 0xdf, 0xb7, 0x34, 0xa7, 0x24, 0xb3, 0x20, 0x27, 0x95, 0x08, 0xfb,
	0x95, 0xdc, 0xb8, 0x04, 0x10, 0xca, 0xc9, 0xb7, 0xd6, 0x68, 0x12, 0x23, 0x97, 0xa0, 0x33, 0x3c,
	0x00, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xcc, 0xb8, 0x98, 0x1d, 0x53, 0x52, 0x84,
	0xc4, 0xf4, 0x90, 0x42, 0x0b, 0x11, 0x30, 0x52, 0xe2, 0x18, 0xe2, 0x50, 0x17, 0xb8, 0x72, 0x71,
	0xc0, 0x5c, 0x25, 0x24, 0x8d, 0xac, 0x08, 0xcd, 0x6b, 0x52, 0x32, 0xd8, 0x25, 0x21, 0xc6, 0x24,
	0xb1, 0x81, 0x63, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x2d, 0x66, 0xd2, 0xbd, 0x01,
	0x00, 0x00,
}
